# Site settings
title: Lois Anderson
subtitle: PhD Student
email: sigrun@marine.rutgers.edu
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 71 Dudley Rd
city: New Brunswick
state: NJ
zip_code: 08901-8520
country: USA
phone: 

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/Lois-Anderson
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
